apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "customerapi"
  description: "customer api to retrieve customer data"
  annotations:
    github.com/project-slug: alokkulkarni/customerapi
    backstage.io/techdocs-ref: dir:.
    sonarqube.org/project-key: customerapi
    backstage.io/code-coverage: scm-only
    # backstage.io/source-location: ''
    # backstage.io/managed-by-location: ''
    jenkins.io/job-full-name: "customerapi"
    argocd/app-name: customerapi
    jira.com/project-key: customerapi # The key of the Jira project to track for this entity, or Comma-separated list of Jira project keys optionally prefixed with the instance name
    # jira.com/components: component,component,component # Jira component name separated with a comma. The Roadie Backstage Jira Plugin Jira annotation `/component` is also supported here by default
    # jira.com/filter-ids: 12345,67890 # Jira filter id separated with a comma
    jira.com/incoming-issues-status: Incoming # The name of the status for incoming issues in Jira. Default: New
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/productsandchannels"
  system: alokkulkarni/customerapi
  providesApis:
    - customerapi 
  providedApis:
    - customerapi
